#include "stdafx.h"
#include "NmsVulkanKeyboard.h"
#include "Misc/xrutil.h"
#include "Reimpl/BaseSystem.h"
#include "generated/static_bases.gen.h"
#include "convert.h"
#include <algorithm>
#include <chrono>
#include <windows.h>
using namespace vr;
static double keyboardNow(){ using C=std::chrono::steady_clock; return std::chrono::duration<double>(C::now().time_since_epoch()).count(); }
bool NmsVulkanKeyboard::active=false;

NmsVulkanKeyboard::NmsVulkanKeyboard(const VRVulkanTextureData_t& g,uint64_t value,uint32_t limit,const char* existing,EventDispatch d,TextChanged c)
 :gfx(g),userValue(value),maxLength(limit),dispatch(std::move(d)),changed(std::move(c)),text(existing?existing:""){
	const char* rows[]={"1|2|3|4|5|6|7|8|9|0|Back","q|w|e|r|t|y|u|i|o|p","a|s|d|f|g|h|j|k|l","Shift|z|x|c|v|b|n|m|.|-","Space|Cancel|Done"};
	for(auto row:rows){rowStart.push_back((int)keys.size());std::string s(row);size_t from=0;while(true){size_t to=s.find('|',from);keys.push_back(s.substr(from,to==std::string::npos?to:to-from));if(to==std::string::npos)break;from=to+1;}rowCount.push_back((int)keys.size()-rowStart.back());}
	active=true;pixels.resize(width*height*4);createResources();render();upload();
}
NmsVulkanKeyboard::~NmsVulkanKeyboard(){active=false;destroyResources();}
uint32_t NmsVulkanKeyboard::memoryType(uint32_t bits,VkMemoryPropertyFlags wanted)const{VkPhysicalDeviceMemoryProperties p{};vkGetPhysicalDeviceMemoryProperties(gfx.m_pPhysicalDevice,&p);for(uint32_t i=0;i<p.memoryTypeCount;++i)if((bits&(1u<<i))&&(p.memoryTypes[i].propertyFlags&wanted)==wanted)return i;OOVR_ABORT("No suitable Vulkan memory type for keyboard");}
void NmsVulkanKeyboard::createResources(){
	XrSwapchainCreateInfo ci{XR_TYPE_SWAPCHAIN_CREATE_INFO};ci.usageFlags=XR_SWAPCHAIN_USAGE_TRANSFER_DST_BIT;ci.format=VK_FORMAT_B8G8R8A8_SRGB;ci.sampleCount=1;ci.width=width;ci.height=height;ci.faceCount=1;ci.arraySize=1;ci.mipCount=1;OOVR_FAILED_XR_ABORT(xrCreateSwapchain(xr_session.get(),&ci,&swapchain));
	uint32_t count=0;OOVR_FAILED_XR_ABORT(xrEnumerateSwapchainImages(swapchain,0,&count,nullptr));images.resize(count);for(auto& i:images)i.type=XR_TYPE_SWAPCHAIN_IMAGE_VULKAN_KHR;OOVR_FAILED_XR_ABORT(xrEnumerateSwapchainImages(swapchain,count,&count,reinterpret_cast<XrSwapchainImageBaseHeader*>(images.data())));
	VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};bi.size=pixels.size();bi.usage=VK_BUFFER_USAGE_TRANSFER_SRC_BIT;bi.sharingMode=VK_SHARING_MODE_EXCLUSIVE;OOVR_FAILED_VK_ABORT(vkCreateBuffer(gfx.m_pDevice,&bi,nullptr,&staging));VkMemoryRequirements req{};vkGetBufferMemoryRequirements(gfx.m_pDevice,staging,&req);VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=req.size;ai.memoryTypeIndex=memoryType(req.memoryTypeBits,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);OOVR_FAILED_VK_ABORT(vkAllocateMemory(gfx.m_pDevice,&ai,nullptr,&stagingMemory));OOVR_FAILED_VK_ABORT(vkBindBufferMemory(gfx.m_pDevice,staging,stagingMemory,0));
	VkCommandPoolCreateInfo pi{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};pi.flags=VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;pi.queueFamilyIndex=gfx.m_nQueueFamilyIndex;OOVR_FAILED_VK_ABORT(vkCreateCommandPool(gfx.m_pDevice,&pi,nullptr,&commandPool));VkCommandBufferAllocateInfo ca{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};ca.commandPool=commandPool;ca.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;ca.commandBufferCount=1;OOVR_FAILED_VK_ABORT(vkAllocateCommandBuffers(gfx.m_pDevice,&ca,&commandBuffer));
	layer.layerFlags=XR_COMPOSITION_LAYER_BLEND_TEXTURE_SOURCE_ALPHA_BIT;layer.space=xr_space_from_ref_space_type(XR_REFERENCE_SPACE_TYPE_STAGE);layer.eyeVisibility=XR_EYE_VISIBILITY_BOTH;layer.subImage.swapchain=swapchain;layer.subImage.imageRect={{0,0},{(int32_t)width,(int32_t)height}};
	XrSpaceLocation headLocation{XR_TYPE_SPACE_LOCATION};XrResult locateResult=xrLocateSpace(xr_gbl->viewSpace,xr_gbl->floorSpace,xr_gbl->GetBestTime(),&headLocation);if(XR_SUCCEEDED(locateResult)&&(headLocation.locationFlags&XR_SPACE_LOCATION_POSITION_VALID_BIT)&&(headLocation.locationFlags&XR_SPACE_LOCATION_ORIENTATION_VALID_BIT))layer.pose=headLocation.pose;else{layer.pose.orientation.w=1;layer.pose.position={0,1.4f,0};}
	glm::quat head(layer.pose.orientation.w,layer.pose.orientation.x,layer.pose.orientation.y,layer.pose.orientation.z);glm::quat tilt=glm::angleAxis(glm::radians(-10.0f),glm::vec3(1,0,0));glm::vec3 offset=head*glm::vec3(0,-.25f,-1.18f);layer.pose.position.x+=offset.x;layer.pose.position.y+=offset.y;layer.pose.position.z+=offset.z;glm::quat final=head*tilt;layer.pose.orientation=G2X_quat(final);layer.size={.88f,.44f};layers.push_back(reinterpret_cast<XrCompositionLayerBaseHeader*>(&layer));
}
void NmsVulkanKeyboard::destroyResources(){if(!gfx.m_pDevice)return;vkQueueWaitIdle(gfx.m_pQueue);if(commandPool)vkDestroyCommandPool(gfx.m_pDevice,commandPool,nullptr);if(staging)vkDestroyBuffer(gfx.m_pDevice,staging,nullptr);if(stagingMemory)vkFreeMemory(gfx.m_pDevice,stagingMemory,nullptr);if(swapchain)xrDestroySwapchain(swapchain);}
void NmsVulkanKeyboard::render(){
	HDC dc=CreateCompatibleDC(nullptr);BITMAPINFO bmi{};bmi.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);bmi.bmiHeader.biWidth=width;bmi.bmiHeader.biHeight=-(LONG)height;bmi.bmiHeader.biPlanes=1;bmi.bmiHeader.biBitCount=32;bmi.bmiHeader.biCompression=BI_RGB;void* bits=nullptr;HBITMAP bmp=CreateDIBSection(dc,&bmi,DIB_RGB_COLORS,&bits,nullptr,0);HGDIOBJ old=SelectObject(dc,bmp);RECT all{0,0,(LONG)width,(LONG)height};HBRUSH bg=CreateSolidBrush(RGB(18,20,28));FillRect(dc,&all,bg);DeleteObject(bg);SetBkMode(dc,TRANSPARENT);
	HFONT title=CreateFontW(34,0,0,0,FW_SEMIBOLD,FALSE,FALSE,FALSE,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Segoe UI");HFONT keyfont=CreateFontW(30,0,0,0,FW_BOLD,FALSE,FALSE,FALSE,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Segoe UI");SelectObject(dc,title);SetTextColor(dc,RGB(245,245,250));RECT tr{28,18,996,70};std::wstring shown(text.begin(),text.end());if(shown.empty())shown=L"Digite aqui...";DrawTextW(dc,shown.c_str(),-1,&tr,DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS);SelectObject(dc,keyfont);
	const int top=82,rowH=78,gap=8,margin=20;for(int row=0;row<(int)rowStart.size();++row){int n=rowCount[row],usable=width-2*margin-(n-1)*gap;for(int col=0;col<n;++col){int index=rowStart[row]+col,x0=margin+col*usable/n+col*gap,x1=margin+(col+1)*usable/n+col*gap;RECT r{x0,top+row*rowH,x1,top+row*rowH+rowH-gap};HBRUSH br=CreateSolidBrush(index==selected?RGB(255,190,35):RGB(55,61,76));FillRect(dc,&r,br);DeleteObject(br);SetTextColor(dc,index==selected?RGB(20,20,20):RGB(250,250,250));std::string label=keys[index];if(label.size()==1&&shift)label[0]=(char)toupper((unsigned char)label[0]);std::wstring wl(label.begin(),label.end());DrawTextW(dc,wl.c_str(),-1,&r,DT_CENTER|DT_VCENTER|DT_SINGLELINE);}}
	memcpy(pixels.data(),bits,pixels.size());for(size_t i=3;i<pixels.size();i+=4)pixels[i]=242;SelectObject(dc,old);DeleteObject(title);DeleteObject(keyfont);DeleteObject(bmp);DeleteDC(dc);dirty=false;
}
void NmsVulkanKeyboard::upload(){
	void* mapped=nullptr;OOVR_FAILED_VK_ABORT(vkMapMemory(gfx.m_pDevice,stagingMemory,0,pixels.size(),0,&mapped));memcpy(mapped,pixels.data(),pixels.size());vkUnmapMemory(gfx.m_pDevice,stagingMemory);XrSwapchainImageAcquireInfo acq{XR_TYPE_SWAPCHAIN_IMAGE_ACQUIRE_INFO};uint32_t index=0;OOVR_FAILED_XR_ABORT(xrAcquireSwapchainImage(swapchain,&acq,&index));XrSwapchainImageWaitInfo wait{XR_TYPE_SWAPCHAIN_IMAGE_WAIT_INFO};wait.timeout=XR_INFINITE_DURATION;OOVR_FAILED_XR_ABORT(xrWaitSwapchainImage(swapchain,&wait));vkResetCommandBuffer(commandBuffer,0);VkCommandBufferBeginInfo begin{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};begin.flags=VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;OOVR_FAILED_VK_ABORT(vkBeginCommandBuffer(commandBuffer,&begin));VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};b.oldLayout=VK_IMAGE_LAYOUT_UNDEFINED;b.newLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;b.srcQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;b.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;b.image=images[index].image;b.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};vkCmdPipelineBarrier(commandBuffer,VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,0,nullptr,1,&b);VkBufferImageCopy copy{};copy.imageSubresource={VK_IMAGE_ASPECT_COLOR_BIT,0,0,1};copy.imageExtent={width,height,1};vkCmdCopyBufferToImage(commandBuffer,staging,images[index].image,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,1,&copy);VkImageMemoryBarrier ready=b;ready.oldLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;ready.newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;vkCmdPipelineBarrier(commandBuffer,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,0,0,nullptr,0,nullptr,1,&ready);OOVR_FAILED_VK_ABORT(vkEndCommandBuffer(commandBuffer));VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO};si.commandBufferCount=1;si.pCommandBuffers=&commandBuffer;OOVR_FAILED_VK_ABORT(vkQueueSubmit(gfx.m_pQueue,1,&si,VK_NULL_HANDLE));OOVR_FAILED_VK_ABORT(vkQueueWaitIdle(gfx.m_pQueue));XrSwapchainImageReleaseInfo rel{XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO};OOVR_FAILED_XR_ABORT(xrReleaseSwapchainImage(swapchain,&rel));
}
void NmsVulkanKeyboard::sendEvent(vr::EVREventType type,const char* utf8){VREvent_t e{};e.eventType=type;e.data.keyboard.uUserValue=userValue;if(utf8)strncpy_s(e.data.keyboard.cNewInput,utf8,sizeof(e.data.keyboard.cNewInput)-1);dispatch(e);}
void NmsVulkanKeyboard::activate(){std::string key=keys[selected];if(key=="Done"){Close(true);return;}if(key=="Cancel"){Close(false);return;}if(key=="Shift"){shift=!shift;dirty=true;return;}if(key=="Back"){if(!text.empty())text.pop_back();sendEvent(VREvent_KeyboardCharInput,"\b");}else{char ch=key=="Space"?' ':key[0];if(shift)ch=(char)toupper((unsigned char)ch);if(!maxLength||text.size()<maxLength){text.push_back(ch);char s[2]{ch,0};sendEvent(VREvent_KeyboardCharInput,s);}}changed(text);dirty=true;}
void NmsVulkanKeyboard::pollInput(){BaseSystem* sys=GetUnsafeBaseSystem();if(!sys)return;VRControllerState_t state{};TrackedDeviceIndex_t chosen=k_unTrackedDeviceIndexInvalid;for(TrackedDeviceIndex_t i=1;i<k_unMaxTrackedDeviceCount;++i){VRControllerState_t c{};if(sys->GetControllerState(i,&c,sizeof(c))){if(chosen==k_unTrackedDeviceIndexInvalid||sys->GetControllerRoleForTrackedDeviceIndex(i)==TrackedControllerRole_RightHand){state=c;chosen=i;}}}if(chosen==k_unTrackedDeviceIndexInvalid)return;double now=keyboardNow();float x=state.rAxis[0].x,y=state.rAxis[0].y;if(now>=nextMove&&(fabs(x)>.65f||fabs(y)>.65f)){int row=0;while(row+1<(int)rowStart.size()&&selected>=rowStart[row+1])++row;int col=selected-rowStart[row];if(fabs(x)>fabs(y)){col=(col+(x>0?1:-1)+rowCount[row])%rowCount[row];selected=rowStart[row]+col;}else{int nr=std::clamp(row+(y<0?1:-1),0,(int)rowStart.size()-1);col=std::min(col,rowCount[nr]-1);selected=rowStart[nr]+col;}nextMove=now+.18;dirty=true;}int hand=sys->GetControllerRoleForTrackedDeviceIndex(chosen)==TrackedControllerRole_LeftHand?0:1;uint64_t mask=ButtonMaskFromId(k_EButton_SteamVR_Trigger)|ButtonMaskFromId(k_EButton_A);bool pressed=(state.ulButtonPressed&mask)!=0;if(pressed&&!wasPressed[hand])activate();wasPressed[hand]=pressed;}
void NmsVulkanKeyboard::HandleInput(TrackedDeviceIndex_t deviceIndex,const VRControllerState_t& state){
	if(closed)return;BaseSystem* sys=GetUnsafeBaseSystem();if(!sys)return;ETrackedControllerRole role=sys->GetControllerRoleForTrackedDeviceIndex(deviceIndex);int hand=role==TrackedControllerRole_LeftHand?0:role==TrackedControllerRole_RightHand?1:-1;if(hand<0)return;
	TrackedDevicePose_t poses[k_unMaxTrackedDeviceCount]{};sys->GetDeviceToAbsoluteTrackingPose(TrackingUniverseStanding,0,poses,k_unMaxTrackedDeviceCount);if(!poses[deviceIndex].bPoseIsValid)return;XrPosef cp=S2O_om34_pose(poses[deviceIndex].mDeviceToAbsoluteTracking);glm::quat cq(cp.orientation.w,cp.orientation.x,cp.orientation.y,cp.orientation.z);glm::vec3 origin(cp.position.x,cp.position.y,cp.position.z),dir=cq*glm::vec3(0,0,-1);glm::quat kq(layer.pose.orientation.w,layer.pose.orientation.x,layer.pose.orientation.y,layer.pose.orientation.z);glm::quat inv=glm::inverse(kq);glm::vec3 center(layer.pose.position.x,layer.pose.position.y,layer.pose.position.z);glm::vec3 lo=inv*(origin-center),ld=inv*dir;
	if(fabs(ld.z)>.0001f){float t=-lo.z/ld.z;if(t>0){glm::vec3 hit=lo+ld*t;float u=hit.x/layer.size.width+.5f,v=.5f-hit.y/layer.size.height;int py=(int)(v*height);if(u>=0&&u<=1&&py>=82&&py<82+5*78){int row=(py-82)/78,n=rowCount[row],col=std::clamp((int)(u*n),0,n-1),next=rowStart[row]+col;if(next!=selected){selected=next;dirty=true;}}}}
	uint64_t mask=ButtonMaskFromId(k_EButton_SteamVR_Trigger)|ButtonMaskFromId(k_EButton_A);bool pressed=(state.ulButtonPressed&mask)!=0;if(pressed&&!wasPressed[hand])activate();wasPressed[hand]=pressed;
}
const std::vector<XrCompositionLayerBaseHeader*>& NmsVulkanKeyboard::Update(){pollInput();if(dirty&&!closed){render();upload();}return layers;}
void NmsVulkanKeyboard::Close(bool submit){if(closed)return;closed=true;active=false;changed(text);if(submit)sendEvent(VREvent_KeyboardDone);sendEvent(VREvent_KeyboardClosed);}
